minimumReleaseAgeExclude:
  - '@deepseek-ai/dsh-attachment@0.1.5-rc.1'
  - '@deepseek-ai/dsh-brand@0.1.5-rc.1'
overrides:
  '@deepseek-ai/dsh-attachment': 0.1.5-rc.1
  '@deepseek-ai/dsh-brand': 0.1.5-rc.1
